python3 main.py --layer_size=128 \
--notes_range=38 \
--batch_size=256 \
--predict_batch_size=1 \
--Ty=100 \
--epochs=1 \
--embedding_len=1 \
--sequence_example_train_file=/home/ouyangzhihao/sss/AAAI/yk/Wikifonia_basic_rnn_sequence_examples/train/training_melodies.tfrecord \
--sequence_example_eval_file=/home/ouyangzhihao/sss/AAAI/yk/Wikifonia_basic_rnn_sequence_examples/val/eval_melodies.tfrecord \
--maxlen=50 \
--config=basic_rnn \
--run_dir=magenta_logdir/run1 \
--output_dir=generated \
--num_outputs=5 \
--num_steps=10 \
--hparams="batch_size=64,rnn_layer_sizes=[64,64]" \
--primer_melody="[60,-2,60,-2,67,-2,67,-2]"